blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog_post.sitemaps import PostSitemap, TagSitemap

sitemaps = {"post": PostSitemap, "tags": TagSitemap}

urlpatterns = [
    path('admin/', admin.site.urls),
    path("blog/", include("blog_post.urls", namespace="blog")),
    path(
        "sitemap.xml", sitemap, {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap "
    ),
]

blog_post/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostFeed

app_name = "blog"

urlpatterns = [
    # path("", PostList.as_view(), name="post_list"),
    path("", views.post_list, name="post_list"),
    path("tag/<slug:tag_slug>/", views.post_list, name="post_list_by_tag"),
    path(
        "<int:year>/<int:month>/<int:day>/<slug:post>/", views.post_detail,
        name="post_detail"
    ),
    path("<int:post_pk>/share/", views.post_share, name="post_share"),
    path("<int:post_id>/comment/", views.post_comment, name="post_comment"),
    path("searching/", views.post_search, name="post_search"),
    path("feed/", LatestPostFeed(), name="post_feed"),
]

blog_post/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone
from django.urls import reverse
from taggit.managers import TaggableManager

class PublishedManager(models.Manager):
    """
    Менеджер для взаимодействия только опубликованных постов.
    """
    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)

class Post(models.Model):
    """
    Модель для созддания постов.
    """
    class Status(models.TextChoices):
        DRAFT = "DF", "Draft"
        PUBLISHED = "PB", "Published"

    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique_for_date="publish")
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
        related_name="blog_posts"
        )
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(
        max_length=2, choices=Status, default=Status.DRAFT
        )

    objects = models.Manager()
    published = PublishedManager()
    tags = TaggableManager()

    class Meta:
        ordering = ("-publish",)
        indexes = [models.Index(fields=["-publish"]),]
        verbose_name = "Пост"
        verbose_name_plural = "Посты"

    def __str__(self):
        return f"{self.title}"

    def get_absolute_url(self):
        return reverse(
            "blog:post_detail",
            args=[self.publish.year, self.publish.month, self.publish.day,
                  self.slug]
        )

class Comment(models.Model):
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name="comments"
    )
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ("created", )
        indexes = (models.Index(fields=("created",)),)
        verbose_name = "Комментарий"
        verbose_name_plural = "Комментарии"

    def __str__(self):
        return f"Комментарий {self.name} к посту {self.post}"

blog_post/forms.py
from django import forms
from .models import Comment

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25, label="Имя")
    email = forms.EmailField()
    to = forms.EmailField(label="Кому(email)")
    comment = forms.CharField(
        required=False, widget=forms.Textarea, label="Комментарий"
    )

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("name", "email", "body")

class SearchForm(forms.Form):
    search = forms.CharField(label="Поиск")

blog_post/views.py
from django.shortcuts import get_object_or_404, render
from django.core.paginator import Paginator
from django.core.mail import send_mail
from django.views.generic import ListView
from django.views.decorators.http import require_POST
from .forms import EmailPostForm, CommentForm, SearchForm
from .models import Post
from taggit.models import Tag
from django.db.models import Count
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank

class PostList(ListView):
    """
    Представление-класс для обработки всех постов.
    """
    queryset = Post.published.all()
    context_object_name = "posts"
    paginate_by = 3
    template_name = "blog/post/list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            tag_slug = self.request.GET["tag_slug"]
        except AttributeError:
            tag_slug = None
        if tag_slug:
            pass
        context["tags"] = Tag.objects.all()
        print(self.request.GET)
        return context

def post_list(request, tag_slug=None):
    """
    Представление для обработки всех постов.
    """
    posts = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        posts = posts.filter(tags__in=[tag])
    paginator = Paginator(posts, 3)
    page_number = request.GET.get("page", 1)
    posts = paginator.get_page(page_number)
    return render(
        request, "blog/post/list.html",
        {"posts": posts, "tag": tag}
    )

def post_detail(request, year, month, day, post):
    """
    Представление для обработки поста в отдельности.
    """
    post = get_object_or_404(
        Post, publish__year=year, publish__month=month, publish__day=day,
        slug=post, status=Post.Status.PUBLISHED
    )
    comments = post.comments.filter(active=True)
    form = CommentForm()

    # Список похожих постов по тегам
    post_tags_ids = post.tags.values_list("id", flat=True)
    similar_posts = Post.published.filter(
        tags__in=post_tags_ids
    ).exclude(id=post.id)
    similar_posts = similar_posts.annotate(
        same_tags=Count("tags"),
    ).order_by("-same_tags", "-publish")[:4]

    return render(
        request, "blog/post/detail.html",
        {"post": post, "comments": comments, "form": form,
         "similar_posts": similar_posts}
    )

@require_POST # Разрешает тоько метод ПОСТ
def post_comment(request, post_id):
    """
    Опубликовать комментарий к посту.
    Только POST разрешён.
    """
    post = get_object_or_404(
        Post, id=post_id, status=Post.Status.PUBLISHED
    )
    comment = None
    form = CommentForm(request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.save()
    return render(
        request, "blog/post/comment.html",
        {"post": post, "form": form, "comment": comment}
    )

def post_share(request, post_pk):
    """
    Поделиться постом по почте.
    """
    post = get_object_or_404(Post, pk=post_pk, status=Post.Status.PUBLISHED)
    sent = False
    if request.method == "POST":
        form = EmailPostForm(request.POST)
        if form.is_valid():
            clean_data = form.cleaned_data
            post_url =  request.build_absolute_uri(post.get_absolute_url())
            subject = (
                f"{clean_data["name"]} ({clean_data["email"]}) "
                f"Рекомендую тебе почитать {post.title}"
            )
            message = (
                f"Прочти {post.title} по ссылке {post_url}\n"
                f"Коментарии {clean_data["name"]}: {clean_data["comment"]}"
            )
            send_mail(
                subject, message, from_email="My blog <volondss@gmail.com>",
                recipient_list=[clean_data["to"]]
            )
            sent = True
    else:
        form = EmailPostForm()
    return  render(
        request, "blog/post/share.html",
        {"post": post, "form": form, "sent": sent}
    )

def post_search(request):
    """
    Поисковик в постах.
    """
    form = SearchForm()
    search = None
    results = []

    if "search" in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            search = form.cleaned_data["search"]
            search_vector = SearchVector(
                "title", "body", config="russian"
            )
            search_query = SearchQuery(search, config="russian")
            results = Post.published.annotate(
                search=search_vector,
                rank=SearchRank(search_vector, search_query)
            ).filter(search=search_query).order_by("-rank")
    return render(
        request, "blog/post/search.html",
        {"form": form, "search": search, "results": results}
    )

templates/blog/base.html
{% load blog_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>
    {% block title %}
    {% endblock title %}
  </title>
  <link href="{% static 'css/blog.css' %}" rel="stylesheet">
</head>
<body>
<div id="content">
  {% block content %}
  {% endblock content %}
</div>
<div id="sidebar">
  <h2><a href="{% url 'blog:post_list' %}">My blog</a></h2>
  <p>
    Это мой блог.
    Я написал уже {% total_posts %} постов.
  </p>
  <p>
    <a href="{% url 'blog:post_feed' %}">
      Подписаться на мою RSS ленту
    </a>
  </p>
  <p>
    <a href="{% url "blog:post_search" %}">Поиск по постам</a>
  </p>
  <h3>Последние посты</h3>
  {% show_latest_posts 3 %}
  <h3>Самые комментируемые посты:</h3>
  {% get_most_commented_posts 3 as most_commented_posts %}
  <ul>
    {% for post in most_commented_posts %}
    <li>
      <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </li>
    {% endfor %}
  </ul>
</div>
</body>
</html>

templates/blog/post/comment.html
{% extends "blog/base.html" %}

{% block title %}Добавить комментарий{% endblock title %}

{% block content %}
  {% if comment %}
    <h2>Ваш комментарий успешно добавлен.</h2>
    <p><a href="{{ post.get_absolute_url }}">Вернуться к посту.</a></p>
  {% else %}
    {% include "blog/post/includes/comment_form.html" %}
  {% endif %}
{% endblock content %}

templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}
  {{ post.title }}
{% endblock title %}

{% block content %}
  <h1>{{ post.title | truncatewords:10}}</h1>
  <p class="date">
    Published {{ post.publish }} by {{ post.author }}
  </p>
  {{ post.body|markdown }}

  <p>
    <a href="{% url 'blog:post_share' post.pk %}">
      Поделиться постом
    </a>
  </p>

  <h2>Похожие посты</h2>
  {% for post in similar_posts %}
  <p>
    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
  </p>
  {% empty %}
  Похожих постов, покачто, нет.
  {% endfor %}

  {% with comments.count as totat_comments %}
    <h2>Общее количество комментариев - {{ totat_comments }}</h2>
  {% endwith %}

  <h2>Комментарии</h2>
  {% for comment in comments %}
    <div class="comment">
      <p class="info">
        {{ forloop.counter }} комментарий от {{ comment.name }}
        {{ comment.created }}
      </p>
      {{ comment.body|linebreaks }}
    </div>
  {% empty %}
    <p>Тут ещё нет комментариев</p>
  {% endfor %}
  {% include "blog/post/includes/comment_form.html" %}
{% endblock content %}

templates/blog/post/includes/comment_form.html
<h2>Добавить комментарий</h2>
<form action="{% url 'blog:post_comment' post.id %}" method="post">
  <div class="left">
    {{ form.name.as_field_group }}
  </div>
  <div class="left">
    {{ form.email.as_field_group }}
  </div>
  {{ form.body.as_field_group }}
  {% csrf_token %}
  <input type="submit" value="Добавить коммент">
</form>

templates/blog/post/includes/latest_posts.html
<ul>
  {% for post in latest_posts %}
  <li>
    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
  </li>
  {% endfor %}
</ul>

templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}
  My blog
{% endblock title %}

{% block content %}
  <h1>My blog</h1>
{% if tag %}
  <h2>Посты по тегу - "{{ tag.name }}"</h2>
{% endif %}
{% for post in posts %}
  <h2>
    <a href="{{ post.get_absolute_url }}">
      {{ post.title }}
    </a>
  </h2>
    <p class="tags">
      Теги:
      {% for tag in post.tags.all %}
        <a href="{% url 'blog:post_list_by_tag' tag.slug %}">{{ tag.name }}</a>
        {% if not forloop.last %}, {% endif %}
      {% endfor %}  
    </p>
  <p class="date">
    Published {{ post.publish }} by {{ post.author }}
  </p>
  {{ post.body|markdown|truncatewords_html:30 }}
{% endfor %}
{% include "paginator.html" with page=posts %}

{% endblock content %}

templates/blog/post/search.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}Поисковик{% endblock title %}

{% block content %}
  {% if search %}
    <h1>Посты содержащие запрос: {{ search }}</h1>
    <h3>
      {% with results.count as total_results %}
      Найдено {{ total_results }} результатов
      {% endwith %}
    </h3>
    {% for post in results %}
      <h4>
        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
      </h4>
      {{ post.body|markdown|truncatewords_html:12 }}
    {% empty %}
      <p>Для вашего запроса нет результатов.</p>
    {% endfor %}
  {% else %}
    <h1>Поиск в постах</h1>
    <form method="get">
      {{ form.as_p }}
      <input type="submit" value="Искать">
    </form>
  {% endif %}
{% endblock content %}

templates/blog/post/share.html
{% extends "blog/base.html" %}

{% block title %}Поделиться постом{% endblock title %}

{% block content %}
  {% if sent %}
    <h2>Пост удачно отправлен</h2>
    <p>"{{ post.title }}" удачно отправлен {{ form.cleaned_data.to }}</p>
  {% else %}
    <h1>Поделиться постом {{ post.title }} по email</h1>
    <form action="{% url 'blog:post_share' post.pk %}" method="post">
      {{ form.as_p }}
      {% csrf_token %}
      <input type="submit" value="Оправить email">
    </form>
  {% endif %}
{% endblock content %}

templates/paginator.html
<div class="paginator">
  <span class="step-link">
    {% if page.has_previous %}
      <a href="?page={{ page.previous_page_number }}">Previous</a>
    {% endif %}
    <span class="current">
      Page {{ page.number }} of {{ page.paginator.num_pages }}
    </span>
    {% if page.has_next %}
      <a href="?page={{ page.next_page_number }}">Next</a>
    {% endif %}
  </span>
</div>